---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
lint: |
  yamllint tasks
platforms:
  - name: el7
    image: centos:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
provisioner:
  log: true
  name: ansible
  connection_options:
    ansible_user: centos
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
